window.DarkTheme = Blockly.Theme.defineTheme('darkTheme', {
    name: 'darkTheme',
    base: Blockly.Themes.Classic,
    blockStyles: {
        logic_blocks: { colourPrimary: '#7E57C2', colourSecondary: '#9575CD', colourTertiary: '#512DA8' },
        loop_blocks: { colourPrimary: '#42A5F5', colourSecondary: '#64B5F6', colourTertiary: '#1E88E5' },
        math_blocks: { colourPrimary: '#26A69A', colourSecondary: '#4DB6AC', colourTertiary: '#00897B' },
        text_blocks: { colourPrimary: '#FFCA28', colourSecondary: '#FFD54F', colourTertiary: '#FFA000' },
        list_blocks: { colourPrimary: '#26C6DA', colourSecondary: '#4DD0E1', colourTertiary: '#0097A7' },
        variable_blocks: { colourPrimary: '#EF5350', colourSecondary: '#E57373', colourTertiary: '#C62828' },
        procedure_blocks: { colourPrimary: '#8D6E63', colourSecondary: '#A1887F', colourTertiary: '#5D4037' },
    },
    categoryStyles: {
        logic_category: { colour: '#7E57C2' },
        loop_category: { colour: '#42A5F5' },
        math_category: { colour: '#26A69A' },
        text_category: { colour: '#FFCA28' },
        list_category: { colour: '#26C6DA' },
        variable_category: { colour: '#EF5350' },
        procedure_category: { colour: '#8D6E63' },
    },
    componentStyles: {
        workspaceBackgroundColour: '#1e1e1e',
        toolboxBackgroundColour: '#333333',
        toolboxForegroundColour: '#ffffff',
        flyoutBackgroundColour: '#252526',
        flyoutForegroundColour: '#cccccc',
        flyoutOpacity: 0.6,
        scrollbarColour: '#797979',
        insertionMarkerColour: '#ffffff',
        insertionMarkerOpacity: 0.3,
        scrollbarOpacity: 0.4,
        cursorColour: '#d0d0d0',
    },
    startHats: true,
});