window.DefaultTheme = Blockly.Theme.defineTheme('defaultTheme', {
    name: 'defaultTheme',
    base: Blockly.Themes.Classic,
    blockStyles: {
        colour_blocks: {
            colourPrimary: '#F39C12',
            colourSecondary: '#F8C471',
            colourTertiary: '#D68910',
        },
        logic_blocks: {
            colourPrimary: '#3498DB',
            colourSecondary: '#85C1E2',
            colourTertiary: '#2874A6',
        },
        loop_blocks: {
            colourPrimary: '#27AE60',
            colourSecondary: '#82E0AA',
            colourTertiary: '#1E8449',
        },
        math_blocks: {
            colourPrimary: '#9B59B6',
            colourSecondary: '#C39BD3',
            colourTertiary: '#7D3C98',
        },
        text_blocks: {
            colourPrimary: '#16A085',
            colourSecondary: '#76D7C4',
            colourTertiary: '#117A65',
        },
        list_blocks: {
            colourPrimary: '#E74C3C',
            colourSecondary: '#F1948A',
            colourTertiary: '#C0392B',
        },
        variable_blocks: {
            colourPrimary: '#E67E22',
            colourSecondary: '#F0B27A',
            colourTertiary: '#CA6F1E',
        },
        variableDynamic_blocks: {
            colourPrimary: '#E67E22',
            colourSecondary: '#F0B27A',
            colourTertiary: '#CA6F1E',
        },
        procedure_blocks: {
            colourPrimary: '#95A5A6',
            colourSecondary: '#BDC3C7',
            colourTertiary: '#7F8C8D',
        },
        hat_blocks: {
            colourPrimary: '#E74C3C',
            colourSecondary: '#EC7063',
            colourTertiary: '#CB4335',
            hat: 'cap',
        },
    },
    categoryStyles: {
        colour_category: { colour: '#F39C12' },
        list_category: { colour: '#E74C3C' },
        logic_category: { colour: '#3498DB' },
        loop_category: { colour: '#27AE60' },
        math_category: { colour: '#9B59B6' },
        procedure_category: { colour: '#95A5A6' },
        text_category: { colour: '#16A085' },
        variable_category: { colour: '#E67E22' },
        variable_dynamic_category: { colour: '#E67E22' },
    },
    componentStyles: {
        workspaceBackgroundColour: '#ecf0f1',
        toolboxBackgroundColour: '#ffffff',
        toolboxForegroundColour: '#2c3e50',
        flyoutBackgroundColour: '#f8f9fa',
        flyoutForegroundColour: '#34495e',
        flyoutOpacity: 0.6,
        scrollbarColour: '#95a5a6',
        insertionMarkerColour: '#2c3e50',
        insertionMarkerOpacity: 0.35,
        scrollbarOpacity: 0.45,
        cursorColour: '#2c3e50',
        selectedGlowColour: '#3498DB',
        selectedGlowOpacity: 0.3,
        replacementGlowColour: '#27AE60',
        replacementGlowOpacity: 0.3,
    },
    startHats: true,
});